[package]
name = "semantic"
version = "0.1.0"
authors = ["Christoph Herzog <chris@theduke.at>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
archive = ["tar", "flate2"]

media-optimizers = ["oxipng", "mozjpeg"]

default = ["archive"]

[dependencies]
anyhow.workspace = true
futures.workspace = true
factdb.workspace = true
factor_engine.workspace = true
factor_tools.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
uuid = { workspace = true, features = ["v4"] }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }
tracing = { workspace = true }

base64 = "0.13.0"


mime_guess = "2.0.4"
infer = "0.9.0"

# async
tokio-util = { version = "0.7.4", features = ["io", "codec"] }

# http
reqwest = { version =  "0.11.12", default-features = false, features = ["gzip", "json", "rustls-tls", "stream"] }
hyper = { version =  "0.14.20", features = ["server", "http1"] }


jsonwebtoken = { version = "8.1.1" }
axum = "0.5.16"

tower-http = { version = "0.3.4", features = ["trace", "fs", "compression-gzip"] }
dirs = "4.0.0"
tower = "0.4.13"

logfs = { path = "../logfs" }
sha2 = "0.10.6"
serde_path_to_error = "0.1.8"

oxipng = { version = "6.0.1", optional = true, default-features = false, features = ["parallel", "zopfli"] }
mozjpeg = { version = "0.9.4", optional = true }

semantic_core = { path = "../core" }
semantic_extra = { version = "0.1", path = "../plugins/extra", default-features = false }
headers = "0.3.8"

tar = { version =  "0.4.38", optional = true }
flate2 = { version = "1.0.24", optional = true }
rust-embed = { version = "6.4.1", features = ["interpolate-folder-path"] }
ffprobe = "0.3.3"
bytes = "1.2.1"
tracing-futures = "0.2.5"
pin-project-lite = "0.2.9"
image = "0.24.4"
img_hash = { git = "https://github.com/theduke/img_hash.git", version = "3.2.0", branch = "upgrade-image-0.24" }
