[package]
name = "semantic"
version = "0.1.0"
authors = ["Christoph Herzog <chris@theduke.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
webkit = ["webkit2gtk", "javascriptcore-rs", "gtk", "gio", "glib"]
default = []

[dependencies]
base64 = "0.13.0"
serde_json = "1.0.64"

anyhow = { version = "1.0.40", features = ["backtrace"] }
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.18", features = ["fmt"] }

mime_guess = "2.0.3"
infer = "0.5.0"

# async
futures = "0.3.15"
tokio = { version = "1.6.1", features = ["full"] }

# http
reqwest = { version =  "0.11.3", default-features = false, features = ["gzip", "json", "rustls-tls"] }
hyper = { version =  "0.14.9", features = ["server", "http1"] }

# webkit-gtk
webkit2gtk = { version =  "0.14.0", features = [ "v2_4", "v2_6",  "v2_16", "v2_22", "v2_26"] , optional = true }
javascriptcore-rs = { version =  "0.14.0", optional = true }
gtk = { version = "0.14.0", optional = true }
gio = { version = "0.14.0", optional = true }
glib = { version = "0.14.0", optional = true }

factordb = "0.1"
factor_tools = "0.1"

jsonwebtoken = { version = "7.2.0" }
serde = { version = "1.0.127", features = ["derive"] }
axum = "0.2.0"
tower-http = { version =  "0.1.1", features = ["trace", "fs"] }
dirs = "3.0.2"
include_dir = "0.6.1"
tower = "0.4.8"

logfs = { path = "../logfs" }
semantic_core = { path = "../core" }
sha2 = "0.9.6"
structopt = "0.3.23"
uuid = { version = "0.8.2", features = ["v4"] }
url = "2.2.2"
tracing-tree = "0.1.10"
serde_path_to_error = "0.1.5"
