[workspace]
resolver = "3"
members = ["crates/*"]
exclude = [
  # ...
]

[workspace.package]
authors = ["Christoph Herzog <chris@theduke.at>"]
keywords = []
repository = "https://github.com/semantiverse/semantic"
homepage = "https://semantiverse.io"
license = "MIT"
readme = "README.md"
edition = "2024"
rust-version = "1.90"
categories = []

version = "0.0.1"

[workspace.dependencies]

# Repo-local
semantic_data = { path = "crates/data" }


# crates.io

serde = "1.0.228"
serde_json = "1.0.145"
time = "0.3.47"
bytes = "1.11.1"
hex = "0.4.3"
ordered-float = "5.1.0"
sha2 = "0.10.9"
uuid = "1.21.0"
anyhow = "1"
tokio = "1.48.0"
tracing = "0.1.44"
dioxus = "0.7.9"
