[application]
name = "semantic"
default_platform = "desktop"

[web.app]
title = "Semantic"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[[web.proxy]]
backend = "http://127.0.0.1:8888/api"
