[package]
name = "semantic_media"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[features]
default = ["image"]
image = ["dep:image"]

[dependencies]
async-trait = "0.1.89"
bytes = { workspace = true }
ffprobe = "0.4.0"
futures-util = "0.3.31"
image = { version = "=0.25.6", optional = true }
infer = "0.19.0"
serde = { workspace = true, features = ["derive"] }
thiserror = "2.0.17"
tokio = { workspace = true, features = ["fs", "io-util", "rt", "sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
