[package]
name = "semantic_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
console_error_panic_hook = "0.1.6"
tracing = "0.1.29"
tracing-wasm = "0.2.0"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
js-sys = "0.3.55"
serde_json = "1.0.64"
getrandom = { version = "0.2.3", features = ["js"] }
url = "2.2.2"
anyhow = { version = "1.0.41", features = ["backtrace"] }
uuid = { version = "0.8.2", features = ["wasm-bindgen", "v4"] }
rand = "0.8.4"
futures = "0.3.17"

brass = { version =  "0.1" }
# brass_bulma = "0.1"

factordb = { version = "0.1", default-features = false }

semantic_core = { path = "../core" }
semantic_ui_core = { path = "../ui_core" }

semantic_health = { path = "../plugins/health" }
# semantic_contrib = { path = "../contrib" }

[dependencies.web-sys] 
version = "0.3.55"
features = [
  "Event",
  "InputEvent",
  "KeyboardEvent",
  "HtmlInputElement",
  "FileList",
  "File",
  "Headers",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
  "History",
  "HtmlVideoElement",
  "HtmlAudioElement",
  "HtmlMediaElement",
  # Clipboard stuff.
  "ClipboardEvent",
  "DataTransfer",
]
