[package]
name = "semantic_ui"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[features]
default = ["markdown"]
markdown = ["semantic_ui_core/markdown"]
web = ["markdown", "dioxus/web", "semantic_rpc/client-http-web"]
desktop = ["markdown", "dioxus/desktop", "semantic_rpc/client-http-native"]
standalone = [
  "markdown",
  "desktop",
  "dep:async-trait",
  "dep:semantic_app",
  "dep:semantic_db_core",
  "dep:semantic_db_redb",
]

[dependencies]
async-trait = { version = "0.1.89", optional = true }
bytes = { workspace = true }
dioxus = { workspace = true, features = ["router"] }
dioxus-icons = "0.1.0"
dioxus-sdk-time = "0.7.0"
dxcomp = { path = "../dxcomp" }
futures = "0.3.31"
infer = { version = "0.19.0", default-features = false }
semantic_app = { path = "../app", optional = true }
semantic_data = { workspace = true }
semantic_db_core = { path = "../db_core", optional = true }
semantic_db_redb = { path = "../db_redb", optional = true }
semantic_rpc = { path = "../rpc", features = ["client"] }
semantic_ui_core = { path = "../ui_core", default-features = false }
tracing = { workspace = true }
web-sys = { version = "0.3.82", features = ["Blob", "File", "Storage", "Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["fs"] }
tokio-util = { version = "0.7.17", features = ["io"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.105"
