[package]
name = "semantic_ui"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[features]
default = ["markdown"]
markdown = ["semantic_ui_core/markdown"]
web = [
  "markdown",
  "dioxus/web",
  "semantic_rpc/client-http-web",
  "time/wasm-bindgen",
]
desktop = ["markdown", "dioxus/desktop", "semantic_rpc/client-http-native"]
standalone = [
  "markdown",
  "desktop",
  "dep:async-trait",
  "dep:semantic_app",
  "dep:semantic_db_core",
  "dep:semantic_db_redb",
]

[dependencies]
async-trait = { version = "0.1.89", optional = true }
base64 = "0.22.1"
bytes = { workspace = true }
dioxus = { workspace = true, features = ["router"] }
dioxus-icons = "0.1.0"
dioxus-sdk-time = "0.7.0"
dxcomp = { path = "../dxcomp" }
futures = "0.3.31"
infer = { version = "0.19.0", default-features = false }
regex = "1.12.2"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
semantic_app = { path = "../app", optional = true }
semantic_base = { path = "../base" }
semantic_data = { workspace = true }
semantic_db_core = { path = "../db_core", optional = true }
semantic_db_redb = { path = "../db_redb", optional = true }
semantic_rpc = { path = "../rpc", features = ["client"] }
semantic_ui_core = { path = "../ui_core", default-features = false }
time = { workspace = true }
web-time = "1.1.0"
tracing = { workspace = true }
web-sys = { version = "0.3.82", features = ["Blob", "File", "Storage", "Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tempfile = "3.26.0"
tokio = { workspace = true, features = ["fs", "io-util", "macros", "process", "rt", "sync", "time"] }
tokio-util = { version = "0.7.17", features = ["io"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.98"
wasm-bindgen = "=0.2.121"
wasm-bindgen-futures = "0.4.71"
web-sys = { version = "0.3.82", features = [
  "BlobEvent",
  "ClipboardEvent",
  "DataTransfer",
  "DataTransferItem",
  "DataTransferItemList",
  "FileReader",
  "BlobPropertyBag",
  "AudioContext",
  "AudioContextState",
  "AudioNode",
  "AnalyserNode",
  "MediaStreamAudioSourceNode",
  "DomException",
  "Document",
  "Element",
  "DisplayMediaStreamConstraints",
  "HtmlVideoElement",
  "HtmlMediaElement",
  "HtmlCanvasElement",
  "CanvasRenderingContext2d",
  "MediaStreamTrackState",
  "Event",
  "MediaDevices",
  "MediaRecorder",
  "MediaRecorderErrorEvent",
  "MediaRecorderOptions",
  "MediaStream",
  "MediaStreamConstraints",
  "MediaStreamTrack",
  "Navigator",
  "RecordingState",
  "Url",
] }
