[package]
name = "dxform"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
dioxus = { workspace = true }
futures = "0.3.31"
thiserror = "2.0.17"
