[package]
name = "semantic_cli"
version = "0.1.0"
edition = "2021"
default-run = "semantic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "./src/main.rs"
name = "semantic"

[dependencies]
semantic = { version = "0.1", path = "../semantic" }
semantic_core = { version = "0.1.0", path = "../core" }

factdb.workspace = true
factor_tools.workspace = true
factor_engine.workspace = true
anyhow = {workspace = true, features = ["backtrace"]}
futures.workspace = true
serde_json.workspace = true
url.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

bytesize = "1.1.0"
sha2 = "0.10.6"
clap = { version = "4.0.2", features = ["derive", "env", "help"] }
tracing-subscriber = { version = "0.3.15", features = ["fmt", "env-filter"] }
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls", "json"] }
is-terminal = "0.3.0"
indicatif = "0.17.1"
human-sort = "0.2.2"
rpassword = "7.2.0"
