[package]
name = "semantic_app"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[features]
default = ["base"]
base = ["dep:semantic_base"]

[dependencies]
async-trait = "0.1.89"
bytes = { workspace = true }
futures-util = "0.3.31"
hex = { workspace = true }
objstore = "0.1.0-alpha.3"
objstore_fs = "0.1.0-alpha.3"
ordered-float = { workspace = true }
semantic_data = { workspace = true }
semantic_base = { path = "../base", optional = true }
semantic_db_core = { path = "../db_core" }
semantic_media = { path = "../media" }
semantic_rpc = { path = "../rpc" }
facet-json = "0.43.2"
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
thiserror = "2.0.17"
time = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
url = "2.5.7"
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
