[package]
name = "semantic_ui_core"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
dioxus = { workspace = true }
facet-json = "0.43.2"
futures = "0.3.31"
semantic_data = { workspace = true }
semantic_db_core = { path = "../db_core" }
semantic_rpc = { path = "../rpc", features = ["client"] }
thiserror = "2.0.17"
