[package]
name = "semantic_ui_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brass = { version = "0.1" }
# brass_bulma = "0.1"
factordb = { version = "0.1", default-features = false }
fnv = "1.0.7"
futures = "0.3.16"
js-sys = "0.3.51"
pulldown-cmark = "0.8.0"

serde_json = "1.0.64"
tracing = "0.1.26"
url = "2.2.2"
wasm-bindgen = "0.2.74"
wasm-bindgen-futures = "0.4.24"

semantic_core = { path = "../core" }
once_cell = "1.8.0"
anyhow = "1.0.44"
form_urlencoded = "1.0.1"
chrono = { version = "0.4.19", features = ["wasmbind"] }
base64 = "0.13.0"


[dependencies.web-sys] 
version = "0.3.55"
features = [
    "HtmlVideoElement", 
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "File", 
    "Response", 
    "RequestInit",
    "RequestMode",
    "Request",
    "Headers",
]
