[package]
name = "semantic_ui_core"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[features]
default = ["markdown"]
markdown = ["dep:dxeditor", "dep:pulldown-cmark", "dxeditor/markdown", "dxeditor/web"]

[dependencies]
bytes = { workspace = true }
dioxus = { workspace = true, features = ["router"] }
dioxus-icons = "0.1.0"
dioxus-sdk-time = "0.7.0"
dxcomp = { path = "../dxcomp" }
dxeditor = { path = "../dxeditor", default-features = false, optional = true }
dxform = { path = "../dxform" }
facet-json = "0.43.2"
futures = "0.3.31"
pulldown-cmark = { version = "0.13.0", optional = true }
regex = "1.12.2"
semantic_data = { workspace = true }
semantic_db_core = { path = "../db_core" }
semantic_rpc = { path = "../rpc", features = ["client"] }
thiserror = "2.0.17"
time = { workspace = true, features = ["formatting", "parsing"] }
tracing = { workspace = true }
web-sys = { version = "0.3.82", features = ["Window", "Location"] }

[dev-dependencies]
semantic_base = { path = "../base" }
semantic_db_kv = { path = "../db_kv" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
