[package]
name = "semantic_db_kv"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
async-trait = "0.1.89"
base64 = "0.22.1"
facet = { version = "0.43.2", features = ["time", "uuid", "bytes"] }
facet-json = "0.43.2"
rmp-serde = "1.3.0"
serde = { workspace = true, features = ["derive"] }
semantic_data = { workspace = true }
semantic_db_core = { path = "../db_core" }
tokio = { version = "1.48.0", features = ["rt"], optional = true }
