[package]
name = "semantic_base"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
futures = "0.3.31"

semantic_rpc_core = { path = "../rpc_core" }
semantic_data = { workspace = true }

[dev-dependencies]
semantic_db_kv = { path = "../db_kv" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
semantic_db_core = { path = "../db_core" }
