// This file was auto-generated by factordb.
// DO NOT EDIT MANUALLY


export const FACTOR_ID = "factor/id";
export const FACTOR_IDENT = "factor/ident";
export const FACTOR_TITLE = "factor/title";
export const FACTOR_DESCRIPTION = "factor/description";
export const FACTOR_TYPE = "factor/type";
export const FACTOR_VALUE_TYPE = "factor/valueType";
export const FACTOR_UNIQUE = "factor/unique";
export const FACTOR_INDEX = "factor/index";
export const FACTOR_IS_STRICT = "factor/isStrict";
export const FACTOR_ENTITY_ATTRIBUTES = "factor/entityAttributes";
export const FACTOR_EXTEND = "factor/extend";
export const FACTOR_IS_RELATION = "factor/isRelation";
export const FACTOR_INDEX_ATTRIBUTES = "factor/index_attributes";
export const SEMANTIC_TITLE = "semantic/title";
export const SEMANTIC_DESCRIPTION = "semantic/description";
export const SEMANTIC_URL = "semantic/url";
export const SEMANTIC_PREVIEW_IMAGE_URL = "semantic/preview_image_url";
export const SEMANTIC_USERNAME = "semantic/username";
export const SEMANTIC_BLOB_URI = "semantic/blob_uri";
export const SEMANTIC_MIME_TYPE = "semantic/mime_type";
export const SEMANTIC_HASH = "semantic/hash";
export const SEMANTIC_DURATION = "semantic/duration";
export const SEMANTIC_FILE_SIZE = "semantic/file_size";
export const SEMANTIC_DOWNLOAD_URL = "semantic/download_url";
export const SEMANTIC_FILENAME = "semantic/filename";
export const SEMANTIC_SOCIAL_MEDIA_POST_CONTENT = "semantic/social_media_post_content";
export const SEMANTIC_NOTE_BODY = "semantic/note_body";
export const SEMANTIC_HABIT_OCURRENCE_COMMENT = "semantic/habit_ocurrence_comment";
export const SEMANTIC_HABIT_OCURRENCE_PARENT_ID = "semantic/habit_ocurrence_parent_id";
export const SEMANTIC_HABIT_OCURRENCE_TIME = "semantic/habit_ocurrence_time";
export const SEMANTIC_HABIT_MODE = "semantic/habit_mode";
export const SEMANTIC_COLLECTION_ITEMS = "semantic/collection_items";
export const SEMANTIC_TAG_NAME = "semantic/tag_name";
export const SEMANTIC_TAG_PARENT = "semantic/tag_parent";
export const SEMANTIC_TAGS = "semantic/tags";


export type EntityId = string;
export type Ident = EntityId | string;
export type Url = string;
export type Timestamp = number;
export interface BaseEntity {
  "factor/id": EntityId,
  "factor/ident"?: Ident | null,
  "factor/type"?: string | null,
}


export const TY_FACTOR_ATTRIBUTE = "factor/Attribute";
export interface FactorAttribute extends BaseEntity {
  "factor/type": "factor/Attribute",
  "factor/id": EntityId,
  "factor/ident": string,
  "factor/title"?: string | null,
  "factor/description"?: string | null,
  "factor/valueType": string,
  "factor/unique": boolean,
  "factor/index": boolean,
  "factor/isStrict": boolean,
}


export const TY_FACTOR_ENTITY = "factor/Entity";
export interface FactorEntity extends BaseEntity {
  "factor/type": "factor/Entity",
  "factor/id": EntityId,
  "factor/ident": string,
  "factor/title"?: string | null,
  "factor/description"?: string | null,
  "factor/isStrict": boolean,
  "factor/isRelation": boolean,
  "factor/extend": boolean[],
  "factor/entityAttributes": {attribute: EntityId, cardinality: "Optional" | "Many" | "Required",}[],
}


export const TY_FACTOR_INDEX = "factor/Index";
export interface FactorIndex extends BaseEntity {
  "factor/type": "factor/Index",
  "factor/id": EntityId,
  "factor/ident": string,
  "factor/title"?: string | null,
  "factor/description"?: string | null,
  "factor/index_attributes": EntityId[],
}


export const TY_SEMANTIC_FILE = "semantic/File";
export interface SemanticFile extends BaseEntity {
  "factor/type": "semantic/File",
  "factor/ident"?: string | null,
  "semantic/title"?: string | null,
  "semantic/filename"?: string | null,
  "semantic/file_size"?: number | null,
  "semantic/mime_type"?: string | null,
  "semantic/hash"?: string | null,
  "semantic/url"?: Url | null,
  "semantic/download_url"?: Url | null,
  "semantic/preview_image_url"?: Url | null,
  "semantic/blob_uri"?: string | null,
}


export const TY_SEMANTIC_IMAGE = "semantic/Image";
export interface SemanticImage extends Omit<SemanticFile, "factor/type"> {
  "factor/type": "semantic/Image",
}


export const TY_SEMANTIC_VIDEO = "semantic/Video";
export interface SemanticVideo extends Omit<SemanticFile, "factor/type"> {
  "factor/type": "semantic/Video",
  "semantic/duration"?: number | null,
}


export const TY_SEMANTIC_SOCIAL_MEDIA_POST = "semantic/SocialMediaPost";
export interface SemanticSocialMediaPost extends BaseEntity {
  "factor/type": "semantic/SocialMediaPost",
  "factor/ident"?: string | null,
  "semantic/title"?: string | null,
  "semantic/url"?: Url | null,
  "semantic/username"?: string | null,
  "semantic/social_media_post_content": EntityId[],
}


export const TY_SEMANTIC_NOTE = "semantic/Note";
export interface SemanticNote extends BaseEntity {
  "factor/type": "semantic/Note",
  "semantic/title": string,
  "semantic/note_body": string,
}


export const TY_SEMANTIC_HABIT = "semantic/Habit";
export interface SemanticHabit extends BaseEntity {
  "factor/type": "semantic/Habit",
  "semantic/title": string,
  "semantic/description"?: string | null,
  "semantic/habit_mode": "positive" | "negative" | "neutral",
}


export const TY_SEMANTIC_HABIT_OCCURENCE = "semantic/HabitOccurence";
export interface SemanticHabitOccurence extends BaseEntity {
  "factor/type": "semantic/HabitOccurence",
  "semantic/habit_ocurrence_parent_id": EntityId,
  "semantic/habit_ocurrence_time": Timestamp,
  "semantic/habit_mode": "positive" | "negative" | "neutral",
  "semantic/habit_ocurrence_comment"?: string | null,
}


export const TY_SEMANTIC_COLLECTION = "semantic/Collection";
export interface SemanticCollection extends BaseEntity {
  "factor/type": "semantic/Collection",
  "factor/ident"?: string | null,
  "semantic/url"?: Url | null,
  "semantic/title": string,
  "semantic/description"?: string | null,
  "semantic/collection_items": EntityId[],
}


export const TY_SEMANTIC_TAG = "semantic/Tag";
export interface SemanticTag extends BaseEntity {
  "factor/type": "semantic/Tag",
  "semantic/tag_name": string,
  "semantic/description"?: string | null,
  "semantic/tag_parent"?: EntityId | null,
}