use std::collections::{BTreeMap, HashMap, VecDeque};
use std::io::Write;

use facet::{Def, Facet, NumericType, Shape, StructKind, Type, UserType};
use semantic_data::schema::Package;

fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let mut args = std::env::args().skip(1);
    let target = args.next().unwrap_or_else(|| "base".to_string());
    let output = args.next();
    let mut writer: Box<dyn Write> = match output {
        Some(path) => Box::new(std::io::BufWriter::new(std::fs::File::create(path)?)),
        None => Box::new(std::io::stdout().lock()),
    };
    match target.as_str() {
        "base" => write_package(&mut writer, &semantic_base::package())?,
        "filestore" => write_package(&mut writer, &semantic_data::filestore::package())?,
        "jobs" => write_package(&mut writer, &semantic_data::jobs::package())?,
        "core" => writer.write_all(generate_core_types().as_bytes())?,
        "--help" | "-h" => {
            println!("usage: semantic_sdk_export [core|base|filestore|jobs] [output]")
        }
        other => {
            return Err(format!(
                "unknown target '{other}' (expected core, base, filestore or jobs)"
            )
            .into());
        }
    }
    Ok(())
}

fn write_package(
    mut writer: impl Write,
    package: &Package,
) -> std::result::Result<(), Box<dyn std::error::Error>> {
    let json = facet_json::to_string(package)?;
    writer.write_all(json.as_bytes())?;
    writer.write_all(b"\n")?;
    Ok(())
}

fn generate_core_types() -> String {
    let roots = [
        <semantic_data::schema::Package as Facet>::SHAPE,
        <semantic_db_core::Query as Facet>::SHAPE,
        <semantic_db_core::QueryResult as Facet>::SHAPE,
        <semantic_db_core::Entity as Facet>::SHAPE,
        <semantic_db_core::BatchOperation as Facet>::SHAPE,
        <semantic_db_core::BatchOutcome as Facet>::SHAPE,
        <semantic_db_core::BatchReturn as Facet>::SHAPE,
        <semantic_db_core::BatchReply as Facet>::SHAPE,
        <semantic_db_core::BatchReturnErrorReason as Facet>::SHAPE,
        <semantic_db_core::ValidationError as Facet>::SHAPE,
        <semantic_db_core::ValidationViolation as Facet>::SHAPE,
        <semantic_data::jobs::JobRecord as Facet>::SHAPE,
        <semantic_data::jobs::JobListQuery as Facet>::SHAPE,
        <semantic_data::jobs::JobListPage as Facet>::SHAPE,
        <semantic_data::jobs::JobKindDescriptor as Facet>::SHAPE,
        <semantic_data::jobs::ClearCompletedResult as Facet>::SHAPE,
        <semantic_data::query::QueryInput as Facet>::SHAPE,
    ];
    let mut output = TypeScriptGenerator::new().render(&roots);
    output.push_str(include_str!("jobs_commands.ts"));
    output
}

struct TypeScriptGenerator {
    names: HashMap<usize, String>,
    owners: BTreeMap<String, usize>,
    queue: VecDeque<&'static Shape>,
}

impl TypeScriptGenerator {
    fn new() -> Self {
        Self {
            names: HashMap::new(),
            owners: BTreeMap::new(),
            queue: VecDeque::new(),
        }
    }

    fn render(mut self, roots: &[&'static Shape]) -> String {
        for shape in roots {
            self.named(shape);
        }
        let mut declarations = Vec::new();
        while let Some(shape) = self.queue.pop_front() {
            let name = self.names[&Self::key(shape)].clone();
            let ty = self.inline(shape);
            let docs = if shape.doc.is_empty() {
                String::new()
            } else {
                format!("/** {} */\n", shape.doc.join(" ").replace("*/", "*\\/"))
            };
            declarations.push(format!("{docs}export type {name} = {ty};"));
        }
        format!(
            "// Generated by semantic_sdk_export. Do not edit.\nimport type {{ SemanticObject, SemanticValue }} from \"../types.js\";\n\n{}\n",
            declarations.join("\n\n")
        )
    }

    fn key(shape: &Shape) -> usize {
        std::ptr::from_ref(shape).addr()
    }

    fn named(&mut self, shape: &'static Shape) -> String {
        if self.is_semantic_value(shape) {
            return "SemanticValue".to_string();
        }
        if self.is_semantic_object(shape) {
            return "SemanticObject".to_string();
        }
        let key = Self::key(shape);
        if let Some(name) = self.names.get(&key) {
            return name.clone();
        }
        let simple = ident(shape.rename.unwrap_or(shape.type_identifier));
        let name = match self.owners.get(&simple) {
            None => simple,
            Some(owner) if *owner == key => simple,
            Some(_) => {
                let module = shape
                    .module_path
                    .and_then(|path| path.rsplit("::").next())
                    .unwrap_or("type");
                format!("{}_{}", ident(module), simple)
            }
        };
        self.owners.insert(name.clone(), key);
        self.names.insert(key, name.clone());
        self.queue.push_back(shape);
        name
    }

    fn reference(&mut self, shape: &'static Shape) -> String {
        if self.is_semantic_value(shape) {
            return "SemanticValue".to_string();
        }
        if self.is_semantic_object(shape) {
            return "SemanticObject".to_string();
        }
        if shape.inner.is_some()
            || !matches!(shape.ty, Type::User(_))
            || matches!(
                shape.def,
                Def::Scalar
                    | Def::Map(_)
                    | Def::Set(_)
                    | Def::List(_)
                    | Def::Array(_)
                    | Def::Slice(_)
                    | Def::Option(_)
                    | Def::Result(_)
                    | Def::Pointer(_)
                    | Def::DynamicValue(_)
            )
        {
            return self.inline(shape);
        }
        self.named(shape)
    }

    fn inline(&mut self, shape: &'static Shape) -> String {
        if shape.type_identifier == "DateTime"
            && shape
                .module_path
                .is_some_and(|path| path.contains("semantic_data::value"))
        {
            // The SDK decodes tagged date_time values to epoch nanoseconds.
            return "number | bigint".to_string();
        }
        if self.is_semantic_value(shape) {
            return "SemanticValue".to_string();
        }
        if self.is_semantic_object(shape) {
            return "SemanticObject".to_string();
        }
        match shape.def {
            Def::Scalar if matches!(shape.ty, Type::User(UserType::Opaque)) => {
                return match shape.type_identifier {
                    "String" | "str" | "char" | "Uuid" | "IpAddr" => "string".to_string(),
                    "Bytes" => "Uint8Array".to_string(),
                    _ => shape
                        .builder_shape
                        .map(|builder| self.reference(builder))
                        .unwrap_or_else(|| "unknown".to_string()),
                };
            }
            Def::Option(def) => return format!("{} | null", self.reference(def.t)),
            Def::List(def) => return format!("Array<{}>", self.reference(def.t)),
            Def::Set(def) => return format!("Set<{}>", self.reference(def.t)),
            Def::Map(def) => {
                let key = self.reference(def.k);
                let value = self.reference(def.v);
                return if key == "string" {
                    format!("Record<string, {value}>")
                } else {
                    format!("Map<{key}, {value}>")
                };
            }
            Def::Array(def) => return format!("Array<{}>", self.reference(def.t)),
            Def::Slice(def) => return format!("Array<{}>", self.reference(def.t)),
            Def::Pointer(def) => {
                return def
                    .pointee
                    .map(|inner| self.reference(inner))
                    .unwrap_or_else(|| "unknown".to_string());
            }
            Def::Result(def) => {
                let ok = self.reference(def.t);
                let err = self.reference(def.e);
                return format!("{{ ok: {ok} }} | {{ err: {err} }}");
            }
            Def::DynamicValue(_) => return "unknown".to_string(),
            _ => {}
        }
        if let Some(inner) = shape.inner {
            return self.reference(inner);
        }
        match shape.ty {
            Type::Primitive(facet::PrimitiveType::Boolean) => "boolean".to_string(),
            Type::Primitive(facet::PrimitiveType::Never) => "never".to_string(),
            Type::Primitive(facet::PrimitiveType::Textual(_)) => "string".to_string(),
            Type::Primitive(facet::PrimitiveType::Numeric(NumericType::Float)) => {
                "number".to_string()
            }
            Type::Primitive(facet::PrimitiveType::Numeric(NumericType::Integer { .. })) => {
                if shape
                    .layout
                    .sized_layout()
                    .is_ok_and(|layout| layout.size() > 4)
                {
                    "number | bigint".to_string()
                } else {
                    "number".to_string()
                }
            }
            Type::User(UserType::Struct(ty)) => self.struct_type(ty.kind, ty.fields),
            Type::User(UserType::Enum(ty)) => ty
                .variants
                .iter()
                .map(|variant| {
                    let name = json_string(variant.effective_name());
                    match variant.data.kind {
                        StructKind::Unit => name,
                        StructKind::Tuple | StructKind::TupleStruct
                            if variant.data.fields.len() == 1 =>
                        {
                            format!(
                                "{{ {name}: {} }}",
                                self.reference(variant.data.fields[0].shape.get())
                            )
                        }
                        _ => format!(
                            "{{ {name}: {} }}",
                            self.struct_type(variant.data.kind, variant.data.fields)
                        ),
                    }
                })
                .collect::<Vec<_>>()
                .join(" | "),
            _ => "unknown".to_string(),
        }
    }

    fn struct_type(&mut self, kind: StructKind, fields: &'static [facet::Field]) -> String {
        match kind {
            StructKind::Unit => "Record<string, never>".to_string(),
            StructKind::Tuple | StructKind::TupleStruct if fields.is_empty() => {
                "undefined".to_string()
            }
            StructKind::Tuple | StructKind::TupleStruct => format!(
                "[{}]",
                fields
                    .iter()
                    .map(|field| self.reference(field.shape.get()))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            StructKind::Struct => format!(
                "{{ {} }}",
                fields
                    .iter()
                    .filter(|field| !field.flags.contains(facet::FieldFlags::SKIP))
                    .map(|field| format!(
                        "{}: {}",
                        json_string(field.rename.unwrap_or(field.name)),
                        self.reference(field.shape.get())
                    ))
                    .collect::<Vec<_>>()
                    .join("; ")
            ),
        }
    }

    fn is_semantic_value(&self, shape: &Shape) -> bool {
        shape.type_identifier == "Value"
            && shape
                .module_path
                .is_some_and(|path| path.contains("semantic_data::value"))
    }

    fn is_semantic_object(&self, shape: &Shape) -> bool {
        shape.type_identifier == "Object"
            && shape
                .module_path
                .is_some_and(|path| path.contains("semantic_data::value"))
    }
}

fn ident(value: &str) -> String {
    let mut output = String::new();
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_alphanumeric() || character == '_' || character == '$' {
            if index == 0 && character.is_ascii_digit() {
                output.push('_');
            }
            output.push(character);
        } else {
            output.push('_');
        }
    }
    if output.is_empty() {
        "_".to_string()
    } else {
        output
    }
}

fn json_string(value: &str) -> String {
    format!("{:?}", value)
}

#[cfg(test)]
mod tests {
    use super::{generate_core_types, write_package};

    #[test]
    fn exports_root_and_nested_schema_members() {
        let package = semantic_base::package();
        let mut output = Vec::new();
        write_package(&mut output, &package).expect("base package should serialize");
        let output = String::from_utf8(output).expect("facet json should be utf-8");
        assert!(output.contains("semantic.base"));
        assert!(output.contains("attributes"));
        assert!(output.contains("classes"));
        assert!(output.contains("strict_schema"));
    }

    #[test]
    fn recursively_generates_core_query_types() {
        let output = generate_core_types();
        assert!(output.contains("export type Query ="));
        assert!(output.contains("export type QueryField ="));
        assert!(output.contains("wildcard"));
        assert!(output.contains("export type Package ="));
    }

    #[test]
    fn jobs_types_match_decoded_rpc_values() {
        let output = generate_core_types();
        assert!(output.contains("export type DateTime = number | bigint;"));
        assert!(output.contains("\"total\": number | bigint | null"));
        assert!(output.contains("\"error\": JobError | null"));
        assert!(output.contains("\"description\": string | null"));
        assert!(
            output.contains(
                "\"semantic.jobs.get\": { params: JobIdParams; result: JobRecord | null }"
            )
        );
        assert!(output.contains("cursor?: JobListCursorInput | null"));
        assert!(!output.contains("semantic:jobs:job:"));
    }
}
