// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Batch {
  actions: Array<Mutate>;
}

export type Mutate =
  | { Create: Create }
  | { Replace: Replace }
  | { Merge: Merge }
  | { Patch: EntityPatch }
  | { Delete: Delete };

export interface Select {
  filter: Expr | null;
  joins: Array<Join>;
  sort: Array<Sort>;
  variables: Record<string, Value>;
  limit: bigint;
  offset: bigint;
  cursor: Id | null;
}

export type Id = string;

export type IdOrIdent = Id | string;

export interface Item<T = Record<string, any>> {
  data: T;
  joins: Array<JoinItem<T>>;
}

export interface Page<T> {
  items: Array<T>;
  next_cursor: Id | null;
}

export type Timestamp = bigint;

export type Value =
  | null
  | boolean
  | number
  | string
  | Value[]
  | { [property: string]: Value };

export type Expr =
  | { InheritsEntityType: string }
  | { Literal: Value }
  | { List: Array<Expr> }
  | { Attr: IdOrIdent }
  | { Ident: IdOrIdent }
  | { Variable: string }
  | { UnaryOp: { op: UnaryOp; expr: Expr } }
  | { BinaryOp: { left: Expr; op: BinaryOp; right: Expr } }
  | { If: { value: Expr; then: Expr; or: Expr } };

export type UnaryOp = "Not";

export type BinaryOp =
  | "And"
  | "Or"
  | "Eq"
  | "Neq"
  | "Gt"
  | "Gte"
  | "Lt"
  | "Lte"
  | "In"
  | "Contains"
  | "RegexMatch";

export interface Sort {
  on: Expr;
  order: Order;
}

export interface DbSchema {
  attributes: Array<AttributeSchema>;
  entities: Array<EntitySchema>;
  indexes: Array<IndexSchema>;
}

export interface AttributeSchema {
  "factor/id": Id;
  "factor/ident": string;
  "factor/title": string | null;
  "factor/description": string | null;
  "factor/valueType": ValueType;
  "factor/unique": boolean;
  "factor/index": boolean;
  "factor/isStrict": boolean;
}

export interface EntitySchema {
  "factor/id": Id;
  "factor/ident": string;
  "factor/title": string | null;
  "factor/description": string | null;
  "factor/entityAttributes": Array<EntityAttribute>;
  "factor/extend": Array<IdOrIdent>;
  "factor/isStrict": boolean;
}

export interface EntityAttribute {
  attribute: IdOrIdent;
  cardinality: Cardinality;
}

export type Cardinality = "Optional" | "Required" | "Many";

export interface IndexSchema {
  "factor/id": Id;
  "factor/ident": string;
  "factor/title": string | null;
  "factor/index_attributes": Array<Id>;
  "factor/description": string | null;
  "factor/unique": boolean;
}

export type ValueType =
  | "Any"
  | "Unit"
  | "Bool"
  | "Int"
  | "UInt"
  | "Float"
  | "String"
  | "Bytes"
  | { List: ValueType }
  | { Map: MapType }
  | { Union: Array<ValueType> }
  | { Object: ObjectType }
  | "DateTime"
  | "Url"
  | "Ref"
  | { Const: Value };

export interface ObjectType {
  name: string | null;
  fields: Array<ObjectField>;
}

export interface ObjectField {
  name: string;
  value_type: ValueType;
}

export interface MapType {
  key: ValueType;
  value: ValueType;
}

export type Patch = Array<PatchOp>;

export type PatchPath = Array<PatchPathElem>;

export type PatchPathElem = { Key: string } | { ListIndex: number };

export type PatchOp =
  | { Add: { path: PatchPath; value: Value } }
  | {
      Replace: {
        path: PatchPath;
        new_value: Value;
        current_value: Value | null;
        must_replace: boolean;
      };
    }
  | { Remove: { path: PatchPath; value: Value | null } };

export interface Join {
  name: string;
  attr: IdOrIdent;
  limit: bigint;
  flatten_relation: boolean;
}

export type Order = "Asc" | "Desc";

export interface JoinItem<T> {
  name: string;
  items: Array<Item<T>>;
}

export interface Create {
  id: Id;
  data: Record<string, any>;
}

export interface Delete {
  id: Id;
}

export interface Merge {
  id: Id;
  data: Record<string, any>;
}

export interface EntityPatch {
  id: Id;
  patch: Patch;
}

export interface Replace {
  id: Id;
  data: Record<string, any>;
}

export type Query =
  | { ServerStatus: null }
  | { Initialize: BackendConfig }
  | { CloseBackend: null }
  | { Select: Select }
  | { Mutate: Mutate }
  | { Batch: Batch }
  | { Schema: null }
  | { PluginSourceCreate: PluginSource }
  | { PluginSourceUpdate: PluginSource }
  | { PluginSourceValidate: PluginSource }
  | { PluginDelete: PluginDelete }
  | { PluginTestFetch: PluginTestFetch }
  | { TagCreate: TagCreate }
  | { Import: ImportJob }
  | { FetchUrl: FetchUrlJob }
  | { OptimiseVideo: OptimiseVideo }
  | { FileDiscardUnOptimized: FileDiscardUnOptimized }
  | { FileDiscardOptimised: FileDiscardUnOptimized }
  | { FileCreatePreviewImageBlob: FileCreatePreviewImageBlob }
  | { HttpFetch: SimpleHttpRequest }
  | { JobStatus: string }
  | { ConvertFile: ConvertFile }
  | { FindUnusedBlobs: null }
  | { DeleteUnusedBlobs: null }
  | { AnalyzeMedia: { force: boolean } };

export interface TagCreate {
  name: string;
}

export type ApiResponse<T = Reply> = { Ok: T } | { Err: ApiError };

export interface ApiError {
  message: string;
  code: string | null;
  details: string | null;
}

export interface PluginDelete {
  name: string;
}

export interface FileDiscardUnOptimized {
  file_id: Id;
}

export interface SimpleHttpRequest {
  url: string;
  method: string;
  headers: Record<string, string>;
  body: Array<number> | null;
}

export interface SimpleHttpResponse {
  status: number;
  headers: Record<string, string>;
  body: string | null;
}

export interface BackendConfig {
  db: DbConfig;
  idle_timeout: bigint | null;
}

export interface BlobInfo {
  key: string;
  size: bigint;
}

export interface PluginTestFetch {
  runtime: string;
  code: string;
  url: string;
}

export interface OptimiseVideo {
  video_id: Id;
}

export interface UnusedBlobsDeleted {
  count: bigint;
  reclaimed_size: bigint;
}

export interface FileCreatePreviewImageBlob {
  file_id: Id;
  data: string;
  mime_type: string;
}

export interface SemanticSchema {
  db: DbSchema;
}

export interface BackendStatus {
  db_size: bigint | null;
  asset_size: bigint | null;
  storage_size: bigint | null;
}

export type DbConfig = { Crypto: BackendCryptoConfig };

export interface BackendCryptoConfig {
  data_path: string | null;
  key: string;
  key_iterations: number | null;
  salt: string | null;
  raw: boolean;
  offset: bigint | null;
}

export interface Job {
  id: string;
  name: string;
  created_at: Timestamp;
  started_at: Timestamp | null;
  finished_at: Timestamp | null;
  steps: Array<JobStep>;
  status: JobStatus;
}

export interface JobStep {
  name: string;
  started_at: Timestamp | null;
  finished_at: Timestamp | null;
}

export type JobStatus =
  | { Queued: { queue_position: bigint | null } }
  | {
      Running: {
        step: string | null;
        progress_percent: number | null;
        progress_message: string | null;
      };
    }
  | { Finished: { result: { Ok: string } | { Err: ApiError } } };

export interface ServerStatus {
  backend_initialized: boolean;
  backend_status: BackendStatus | null;
}

export interface OptimiseVideoReply {
  job_id: string;
}

export interface ConvertFile {
  file_id: Id;
  target_format: string;
  settings: any | null | undefined;
}

export interface FetchUrlOutput {
  items: Array<Item>;
  load_more_url: RelatedUrl | null;
  related_urls: Array<RelatedUrl>;
  related_items: Array<Item>;
}

export interface ImportJob {
  url: string;
  import_media: boolean;
}

export interface FetchUrlJob {
  url: string;
}

export interface RelatedUrl {
  label: string;
  url: string;
}

export interface ImportOutput {
  items: Array<Item>;
}

export interface PluginSource {
  "factor/id": Id;
  "factor/ident": string;
  "semantic/plugin_runtime": string | null;
  "semantic/plugin_code": string | null;
  "semantic/plugin_strict_validation": boolean;
  "semantic/comment": string | null;
}

export type Reply =
  | { ServerStatus: ServerStatus }
  | { Initialize: SemanticSchema }
  | { CloseBackend: null }
  | { Select: Page<Item> }
  | { Mutate: null }
  | { Batch: null }
  | { Schema: SemanticSchema }
  | { PluginSourceCreate: PluginSource }
  | { PluginSourceUpgrade: PluginSource }
  | { PluginSourceValidate: null }
  | { PluginDelete: null }
  | { PluginTestFetch: FetchUrlOutput | null }
  | { TagCreate: Record<string, any> }
  | { Import: ImportOutput }
  | { FetchUrl: FetchUrlOutput }
  | { HttpFetch: SimpleHttpResponse }
  | { OptimiseVideo: OptimiseVideoReply }
  | { FileDiscardOptimised: null }
  | { FileDiscardUnOptimised: null }
  | { FileCreatePreviewImageBlob: null }
  | { JobStatus: Job }
  | { ConvertFile: Job }
  | { FindUnusedBlobs: { items: Array<BlobInfo> } }
  | { DeleteUnusedBlobs: UnusedBlobsDeleted }
  | { AnalyzeMedia: null };
