[package]
name = "semantic_db_redb"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
redb = "2.6.3"
semantic_db_kv = { path = "../db_kv" }
semantic_data = { workspace = true }
