[package]
name = "semantic_db"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1.89"
tokio = { version = "1.48.0", features = ["sync"] }
semantic_db_core = { path = "../db_core" }
semantic_db_kv = { path = "../db_kv" }
semantic_data = { workspace = true }
