[package]
name = "semantics"
version = "0.1.0"
authors = ["Christoph Herzog <chris@theduke.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.40", features = ["backtrace"] }
futures = "0.3.15"
tokio = { version = "1.6.1", features = ["full"] }

semantics_core = { path = "../semantics_core" }
