[package]
name = "semantic_rpc_core"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
semantic_data = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = "2.0.17"

[dev-dependencies]
serde_json = { workspace = true }
