[package]
name = "semantic_core"
version = "0.1.0"
authors = ["Christoph Herzog <chris@theduke.at>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
schema = [ "schemars", "ts-rs", "factdb/jsonschema", "factdb/typescript-schema" ]

[dependencies]
factdb.workspace = true
anyhow.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }
url = { workspace = true, features = ["serde"] }
tracing.workspace = true

chrono = { version = "0.4.22", features = ["serde"] }

base64 = "0.13.0"
# FIXME: use normal crate once https://github.com/GREsau/schemars/pull/141 is merged upstream.
schemars = { version = "0.8.8", features = ["chrono", "uuid1", "url", "ordered-float"], optional = true, git = "https://github.com/theduke/schemars", branch = "ordered-float" }
ts-rs = { version = "6.2.0", default-features = false, features = ["serde-compat", "chrono-impl", "uuid-impl", "ordered-float-impl"], optional = true }
