[package]
name = "dxgraph"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[features]
default = []
web = ["dep:web-sys"]

[dependencies]
dioxus = { workspace = true }
dioxus-sdk-time = "0.7.0"
dxcomp = { path = "../dxcomp" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
indexmap = { version = "2", features = ["serde"] }
thiserror = "2.0.17"
web-sys = { version = "0.3.82", optional = true, features = ["Element", "Performance", "Window"] }

[dev-dependencies]
dioxus-ssr = "0.7.9"
