// This file was auto-generated by factordb.
// DO NOT EDIT MANUALLY


export const FACTOR_ID = "factor/id";
export const FACTOR_IDENT = "factor/ident";
export const FACTOR_TITLE = "factor/title";
export const FACTOR_DESCRIPTION = "factor/description";
export const FACTOR_TYPE = "factor/type";
export const FACTOR_VALUE_TYPE = "factor/valueType";
export const FACTOR_UNIQUE = "factor/unique";
export const FACTOR_INDEX = "factor/index";
export const FACTOR_IS_STRICT = "factor/isStrict";
export const FACTOR_ENTITY_ATTRIBUTES = "factor/entityAttributes";
export const FACTOR_EXTEND = "factor/extend";
export const FACTOR_IS_RELATION = "factor/isRelation";
export const FACTOR_INDEX_ATTRIBUTES = "factor/index_attributes";
export const FACTOR_COUNT = "factor/count";
export const SEMANTIC_TITLE = "semantic/title";
export const SEMANTIC_COMMENT = "semantic/comment";
export const SEMANTIC_DESCRIPTION = "semantic/description";
export const SEMANTIC_URL = "semantic/url";
export const SEMANTIC_PREVIEW_IMAGE_URL = "semantic/preview_image_url";
export const SEMANTIC_PREVIEW_IMAGE_BLOB_URI = "semantic/preview_image_blob_uri";
export const SEMANTIC_USERNAME = "semantic/username";
export const SEMANTIC_TEXT_FORMAT = "semantic/text_format";
export const SEMANTIC_CREATED_AT = "semantic/created_at";
export const SEMANTIC_UPDATED_AT = "semantic/updated_at";
export const SEMANTIC_VISIT_COUNT = "semantic/visit_count";
export const SEMANTIC_LAST_VISIT_TIME = "semantic/last_visit_time";
export const SEMANTIC_NAME = "semantic/name";
export const SEMANTIC_SECONDARY_URL = "semantic/secondary_url";
export const SEMANTIC_PARENT = "semantic/parent";
export const SEMANTIC_EMBEDDED_IN_PARENT = "semantic/embedded_in_parent";
export const SEMANTIC_IMPORTED_AT = "semantic/imported_at";
export const SEMANTIC_MARKDOWN_BODY = "semantic/markdown_body";
export const SEMANTIC_SORT_ORDER = "semantic/sort_order";
export const SEMANTIC_BLOB_URI = "semantic/blob_uri";
export const SEMANTIC_BLOB_URI_WEB = "semantic/blob_uri_web";
export const SEMANTIC_MIME_TYPE = "semantic/mime_type";
export const SEMANTIC_HASH = "semantic/hash";
export const SEMANTIC_ORIGINAL_HASH = "semantic/original_hash";
export const SEMANTIC_DURATION = "semantic/duration";
export const SEMANTIC_FILE_SIZE = "semantic/file_size";
export const SEMANTIC_DOWNLOAD_URL = "semantic/download_url";
export const SEMANTIC_FILENAME = "semantic/filename";
export const SEMANTIC_VIDEO_HAS_SOUND = "semantic/video_has_sound";
export const SEMANTIC_PIXEL_WIDTH = "semantic/pixel_width";
export const SEMANTIC_PIXEL_HEIGHT = "semantic/pixel_height";
export const SEMANTIC_VISUAL_HASH = "semantic/visual_hash";
export const SEMANTIC_SOCIAL_MEDIA_POST_CONTENT = "semantic/social_media_post_content";
export const SEMANTIC_SOCIAL_MEDIA_POST_USER_ID = "semantic/social_media_post_user_id";
export const SEMANTIC_SOCIAL_MEDIA_PLATFORM_NAME = "semantic/social_media_platform_name";
export const SEMANTIC_SOCIAL_MEDIA_PLATFORM_ID = "semantic/social_media_platform_id";
export const SEMANTIC_NOTE_BODY = "semantic/note_body";
export const SEMANTIC_COLLECTION_ITEMS = "semantic/collection_items";
export const SEMANTIC_TAG_NAME = "semantic/tag_name";
export const SEMANTIC_TAG_PARENT = "semantic/tag_parent";
export const SEMANTIC_TAGS = "semantic/tags";
export const SEMANTIC_TASK_DUE_DATE = "semantic.task/due_date";
export const SEMANTIC_TASK_PRIORITY = "semantic.task/priority";
export const SEMANTIC_TASK_COMPLETED_AT = "semantic.task/completed_at";
export const SEMANTIC_GIVEN_NAME = "semantic/given_name";
export const SEMANTIC_FAMILY_NAME = "semantic/family_name";
export const SEMANTIC_BIRTHDATE = "semantic/birthdate";
export const SEMANTIC_GENDER = "semantic/gender";
export const SEMANTIC_LIKE_COUNT = "semantic/like_count";
export const SEMANTIC_IMPORT_URL_MAPPING_SOURCE_URL = "semantic.import_url_mapping/source_url";
export const SEMANTIC_IMPORT_URL_MAPPING_TARGET_URL = "semantic.import_url_mapping/target_url";


export type EntityId = string;
export type Ident = string;
export type IdOrIdent = EntityId | string;
export type Url = string;
export type Timestamp = number;
export interface BaseEntity {
  "factor/id": EntityId,
  "factor/ident"?: Ident | null,
  "factor/type"?: string | null,
}


export const TY_FACTOR_ATTRIBUTE = "factor/Attribute";
export interface FactorAttribute extends BaseEntity {
  "factor/type": "factor/Attribute",
  "factor/id": EntityId,
  "factor/ident": string,
  "factor/title"?: string | null,
  "factor/description"?: string | null,
  "factor/valueType": string,
  "factor/unique": boolean,
  "factor/index": boolean,
  "factor/isStrict": boolean,
}


export const TY_FACTOR_CLASS = "factor/Class";
export interface FactorClass extends BaseEntity {
  "factor/type": "factor/Class",
  "factor/id": EntityId,
  "factor/ident": string,
  "factor/title"?: string | null,
  "factor/description"?: string | null,
  "factor/isStrict": boolean,
  "factor/isRelation": boolean,
  "factor/extend": Ident[],
  "factor/entityAttributes": {attribute: Ident, cardinality: "Optional" | "Required",}[],
}


export const TY_FACTOR_INDEX = "factor/Index";
export interface FactorIndex extends BaseEntity {
  "factor/type": "factor/Index",
  "factor/id": EntityId,
  "factor/ident": string,
  "factor/title"?: string | null,
  "factor/description"?: string | null,
  "factor/index_attributes": EntityId[],
}


export const TY_SEMANTIC_FILE = "semantic/File";
export interface SemanticFile extends BaseEntity {
  "factor/type": "semantic/File",
  "factor/ident"?: string | null,
  "semantic/title"?: string | null,
  "semantic/filename"?: string | null,
  "semantic/file_size"?: number | null,
  "semantic/mime_type"?: string | null,
  "semantic/hash"?: string | null,
  "semantic/original_hash"?: string | null,
  "semantic/url"?: Url | null,
  "semantic/download_url"?: Url | null,
  "semantic/preview_image_url"?: Url | null,
  "semantic/preview_image_blob_uri"?: string | null,
  "semantic/blob_uri"?: string | null,
  "semantic/blob_uri_web"?: string | null,
  "semantic/created_at"?: Timestamp | null,
  "semantic/updated_at"?: Timestamp | null,
  "semantic/imported_at"?: Timestamp | null,
}


export const TY_SEMANTIC_IMAGE = "semantic/Image";
export interface SemanticImage extends Omit<SemanticFile, "factor/type"> {
  "factor/type": "semantic/Image",
  "semantic/pixel_width"?: number | null,
  "semantic/pixel_height"?: number | null,
  "semantic/visual_hash"?: number[] | null,
}


export const TY_SEMANTIC_VIDEO = "semantic/Video";
export interface SemanticVideo extends Omit<SemanticFile, "factor/type"> {
  "factor/type": "semantic/Video",
  "semantic/duration"?: number | null,
  "semantic/video_has_sound"?: boolean | null,
  "semantic/pixel_width"?: number | null,
  "semantic/pixel_height"?: number | null,
}


export const TY_SEMANTIC_AUDIO = "semantic/Audio";
export interface SemanticAudio extends Omit<SemanticFile, "factor/type"> {
  "factor/type": "semantic/Audio",
  "semantic/duration"?: number | null,
}


export const TY_SEMANTIC_SOCIAL_MEDIA_POST = "semantic/SocialMediaPost";
export interface SemanticSocialMediaPost extends BaseEntity {
  "factor/type": "semantic/SocialMediaPost",
  "factor/ident"?: string | null,
  "semantic/title"?: string | null,
  "semantic/username"?: string | null,
  "semantic/social_media_post_user_id"?: EntityId | null,
  "semantic/like_count"?: number | null,
  "semantic/social_media_post_content": EntityId[],
  "semantic/imported_at"?: Timestamp | null,
}


export const TY_SEMANTIC_SOCIAL_MEDIA_ACCOUNT = "semantic/SocialMediaAccount";
export interface SemanticSocialMediaAccount extends Omit<SemanticPerson, "factor/type"> {
  "factor/type": "semantic/SocialMediaAccount",
  "semantic/social_media_platform_name"?: string | null,
  "semantic/social_media_platform_id"?: EntityId | null,
  "semantic/username": string,
  "semantic/imported_at"?: Timestamp | null,
}


export const TY_SEMANTIC_NOTE = "semantic/Note";
export interface SemanticNote extends BaseEntity {
  "factor/type": "semantic/Note",
  "semantic/title": string,
  "semantic/note_body": string,
  "semantic/text_format": "plain" | "markdown",
}


export const TY_SEMANTIC_COLLECTION = "semantic/Collection";
export interface SemanticCollection extends BaseEntity {
  "factor/type": "semantic/Collection",
  "factor/ident"?: string | null,
  "semantic/url"?: Url | null,
  "semantic/title": string,
  "semantic/description"?: string | null,
  "semantic/collection_items": EntityId[],
}


export const TY_SEMANTIC_TAG = "semantic/Tag";
export interface SemanticTag extends BaseEntity {
  "factor/type": "semantic/Tag",
  "semantic/tag_name": string,
  "semantic/description"?: string | null,
  "semantic/tag_parent"?: EntityId | null,
}


export const TY_SEMANTIC_TASK = "semantic/Task";
export interface SemanticTask extends BaseEntity {
  "factor/type": "semantic/Task",
  "semantic/title": string,
  "semantic/markdown_body"?: string | null,
  "semantic/text_format": "plain" | "markdown",
  "semantic/created_at": Timestamp,
  "semantic/updated_at"?: Timestamp | null,
  "semantic/sort_order"?: number | null,
  "semantic.task/priority"?: number | null,
  "semantic.task/due_date"?: Timestamp | null,
}


export const TY_SEMANTIC_PERSON = "semantic/Person";
export interface SemanticPerson extends BaseEntity {
  "factor/type": "semantic/Person",
  "factor/ident"?: string | null,
  "semantic/description"?: string | null,
  "semantic/url"?: Url | null,
  "semantic/name"?: string | null,
  "semantic/given_name"?: string | null,
  "semantic/family_name"?: EntityId | null,
  "semantic/birthdate"?: EntityId | null,
  "semantic/gender"?: "male" | "female" | null,
}


export const TY_SEMANTIC_BOOKMARK = "semantic/Bookmark";
export interface SemanticBookmark extends BaseEntity {
  "factor/type": "semantic/Bookmark",
  "factor/ident"?: string | null,
  "semantic/url": Url,
  "semantic/title"?: string | null,
  "semantic/description"?: string | null,
  "semantic/created_at"?: Timestamp | null,
  "semantic/imported_at"?: Timestamp | null,
}


export const TY_SEMANTIC_IMPORT_URL_MAPPING = "semantic/ImportUrlMapping";
export interface SemanticImportUrlMapping extends BaseEntity {
  "factor/type": "semantic/ImportUrlMapping",
  "semantic/title"?: string | null,
  "semantic.import_url_mapping/source_url": string,
  "semantic.import_url_mapping/target_url": string,
  "semantic/created_at"?: Timestamp | null,
}