[package]
name = "dxcomp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router"] }
dioxus-icons = "0.1.0"
dioxus-primitives = { git = "https://github.com/DioxusLabs/dioxus-components", rev = "02801f27e4b3e30606e5c77e435c9d955c708eb3" }
palette = "0.7.6"
time = { workspace = true, features = ["macros"] }

[dev-dependencies]
dioxus-ssr = "0.7.9"

[features]
default = []
web = ["dioxus/web", "dioxus-primitives/web"]
desktop = ["dioxus/desktop"]
fullstack = ["dioxus/fullstack"]
server = ["dioxus/server", "dioxus/fullstack"]
native = ["dioxus/native"]
