const reserved = new Set([
  // JavaScript and TypeScript keywords.
  "any",
  "as",
  "asserts",
  "async",
  "await",
  "bigint",
  "boolean",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "constructor",
  "continue",
  "debugger",
  "declare",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "get",
  "if",
  "implements",
  "import",
  "in",
  "infer",
  "instanceof",
  "interface",
  "is",
  "keyof",
  "let",
  "module",
  "namespace",
  "never",
  "new",
  "null",
  "number",
  "object",
  "of",
  "package",
  "private",
  "protected",
  "public",
  "readonly",
  "require",
  "return",
  "set",
  "static",
  "string",
  "super",
  "switch",
  "symbol",
  "this",
  "throw",
  "true",
  "try",
  "type",
  "typeof",
  "undefined",
  "unique",
  "unknown",
  "using",
  "var",
  "void",
  "while",
  "with",
  "yield",
  // Imports and globals referenced by generated declarations. Shadowing one
  // of these would silently change the meaning of other generated types.
  "Array",
  "AsyncIterable",
  "Date",
  "Map",
  "Promise",
  "SemanticObject",
  "SemanticValue",
  "Uint8Array",
  "command",
  "packageName",
]);

export const identifier = (name: string): string => {
  const value = name.replace(/[^A-Za-z0-9_$]/g, "_").replace(/^[0-9]/, "_$&");
  const result = value || "_";
  return reserved.has(result) ? `_${result}` : result;
};
