import type { PackageModel } from "./model.js";
import { identifier } from "./identifier.js";
export function renderPackage(model: PackageModel): string {
  const lines = [
    "// Generated by @semantic/sdk. Do not edit.",
    'import { command, type SemanticObject, type SemanticValue } from "@semantic/sdk";',
    "",
  ];
  lines.push(
    `export const packageName = ${JSON.stringify(model.name)} as const;`,
    "",
  );
  const symbols = new Set<string>();
  for (const type of model.types) {
    const symbol = identifier(type.name);
    if (symbols.has(symbol))
      throw new Error(`generated TypeScript symbol collision: ${symbol}`);
    symbols.add(symbol);
    if (type.docs) lines.push(`/** ${type.docs.replaceAll("*/", "*\\/")} */`);
    lines.push(
      `export type ${symbol}${type.params?.length ? `<${type.params.map((param) => `${identifier(param.name)}${param.default === undefined ? "" : ` = ${param.default}`}`).join(", ")}>` : ""} = ${type.type};`,
    );
  }
  if (model.types.length) lines.push("");
  for (const cmd of model.commands) {
    const symbol = identifier(cmd.symbol ?? cmd.name);
    if (symbols.has(symbol))
      throw new Error(`generated TypeScript symbol collision: ${symbol}`);
    symbols.add(symbol);
    if (cmd.docs) lines.push(`/** ${cmd.docs.replaceAll("*/", "*\\/")} */`);
    const payload = cmd.payload
      .map(
        (param) =>
          `${JSON.stringify(param.name)}${param.optional ? "?" : ""}: ${param.type}`,
      )
      .join("; ");
    lines.push(
      `export const ${symbol} = command<{ ${payload} }, ${cmd.output}>(${JSON.stringify(cmd.name)});`,
    );
  }
  return `${lines.join("\n")}\n`;
}
