[package]
name = "semantic_fuse"
authors.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
categories.workspace = true
version.workspace = true

[dependencies]
semantic_rpc_core = { path = "../rpc_core" }
bytes = { workspace = true }
fuser = "0.18.0"
futures = "0.3.31"
hex = { workspace = true }
libc = "0.2.177"
semantic_data = { workspace = true }
semantic_rpc = { path = "../rpc", features = ["client"] }
serde_json = { workspace = true }
serde_yaml = "0.9.34"
sha2 = { workspace = true }
thiserror = "2.0.17"
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
tracing = { workspace = true }
